name: example
description: Driver for the various Flutter Sound examples

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 9.1.6

homepage: https://github.com/canardoux/flutter_sound/blob/master/flutter_sound/

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"



dependencies:
  flutter:
    sdk: flutter

# ============================================================================
# The following instructions are just for developing/debugging Flutter Sound
# Do not put them in a real App
  flutter_sound_platform_interface: # 9.1.6
    path: ../flutter_sound_platform_interface # flutter_sound_platform_interface Dir
  flutter_sound_web: # 9.1.6
    path: ../flutter_sound_web # flutter_sound_web Dir
  flutter_sound: # ^9.1.6
    path: ../ flutter_soundlib # Flutter Sound Dir
# ============================================================================
  flutter_tts: ^3.3.3
  #flutter_iap: ^1.2.3

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.2
  permission_handler: ^6.0.1
  path: ^1.6.4
  #flutter_ffmpeg: ^0.3.1
  intl: ^0.17.0
  just_audio: ^0.9.11
  audio_session: ^0.1.6



dev_dependencies:
 # flutter_test:
#    sdk: flutter
  pedantic: ^1.11.0
  #effective_dart: ^1.3.0

  #display.save( displayObject, options )effective_dart: ^1.0.0
  #lint: ^1.1.1


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  